### ISSUE TITLE
Ctrl/Cmd + K to open search bar

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#10]
Add an event listener inside [`theme.js`](https://github.com/genicsblog/theme-files/blob/main/assets/js/theme.js#L45) at the end, to listen fo key combinations: `Ctrl`+`K` or `Cmd`+ `K`.

If the keys are pressed, call the [`showSearch()` function](https://github.com/genicsblog/theme-files/blob/main/assets/js/theme.js#L45)

**Comment by carrotfarmer** [comment]
@gouravkhunger Can i take this up?

**Comment by gouravkhunger** [comment]
@carrotfarmer sure, I'll assign it to you, thanks 😄
