### ISSUE TITLE
Adding visual info on search bar

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#12]
For #11, we need to show some visual information that pressing `Ctrl + K` will open the search bar. Something like this:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/46792249/154302569-4389805d-9f16-4763-a5ba-54102376db3a.png">

needed changes:
- making a class that has styles to make text appear like keys. Updates in [`theme.css`](https://github.com/genicsblog/theme-files/blob/main/assets/css/theme.css)
- Add the keys in [`search.html`](https://github.com/genicsblog/theme-files/blob/main/_includes/search.html) (should only appear on large screens only)

**Comment by carrotfarmer** [comment]
#13

**Comment by gouravkhunger** [comment]
Fixed in #13
