### ISSUE TITLE
Animation for hamburger

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#15]
Adding a transition animation for the hamburger in the navbar would be a nice addition:

![Screenshot_2022-03-25-01-21-12-760_com android chrome~2](https://user-images.githubusercontent.com/46792249/159998919-48ef29b5-1618-4c07-90d3-5cc7807eebb7.jpg)

**Comment by gouravkhunger** [comment]
probably like this (height and width of bars could change though):

https://user-images.githubusercontent.com/46792249/167085349-9d835f16-a70d-40b4-a175-1d4ab84c8831.mov

**Comment by androlover98** [comment]
I would like to try working on this

**Comment by gouravkhunger** [comment]
hi @androlover98, thanks for your interest!

[These](https://github.com/genicsblog/theme-files/blob/main/_includes/nav.html#L143-L173) are the svgs for the menu. Currently, they are [toggled by hiding](https://github.com/genicsblog/theme-files/blob/main/assets/js/theme.js#L79-L95) one while the other one is active.

You may need to edit the above, along with [the css file](https://github.com/genicsblog/theme-files/blob/main/assets/css/theme.css) for the animation of the bars as well.

P.S. A quick review at [this resource](https://genicsblog.com/gouravkhunger/how-to-create-a-pull-request-in-github-correctly) might help you while making a PR. The imp part here is to make a new branch and not push to the main branch of your fork, as that might help prevent mess.
