### ISSUE TITLE
Fix dark buttons

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#23]
Dark link buttons on [`archive.html`](https://github.com/genicsblog/theme-files/blob/main/_layouts/archive.html#L54) look weird:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/46792249/162368900-88b1d04b-4ab7-43aa-8cef-5847a83ed15f.png">

Needs to be similar style as the [CTA](https://github.com/genicsblog/theme-files/blob/main/_includes/cta.html#L12) (size should be same, needs fix just for the shadow and colour):

<img width="196" alt="image" src="https://user-images.githubusercontent.com/46792249/162369233-dbc9ae02-9a39-48db-9cdf-f3906795a7fd.png">

**Comment by carrotfarmer** [comment]
@gouravkhunger yo can you assign this to me? Also, can you show me the place on the live site where this is found?

**Comment by gouravkhunger** [comment]
sure @carrotfarmer, The dark button is on any category/tag page. [Example](https://genicsblog.com/category/android/) (turn on dark mode btw).

CTA is there on every page.

The fix is just to change button / text colors, and fix shadow.

**Comment by carrotfarmer** [comment]
thanks!
