### ISSUE TITLE
Selection color on code blocks

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#28]
Selection colors specific for code-blocks can be improved.

Dark:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/46792249/163925242-908e0c82-11ab-4aea-8ed8-b9187329a05f.png">

Light:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/46792249/163925314-a1888f54-fd12-46ba-a4c7-d24fddb3349c.png">

**Comment by AnupT16** [comment]
is this issue still up

**Comment by shockz09** [comment]
@AnupT16 yes

**Comment by gouravkhunger** [comment]
@AnupT16 ah, I haven't yet thought of a color scheme, so #37 reverts to default colours. I won't merge it if you guys have some better color scheme that suits well!

**Comment by AnupT16** [comment]
@gouravkhunger I think u are trying to write will not won't

**Comment by shockz09** [comment]
xD lol

**Comment by gouravkhunger** [comment]
I mean the open PR for this selection color fix will not be merged if you guys suggest some suitable color scheme. Sorry for mis understandings, if any 😂

**Comment by gouravkhunger** [comment]
For now, let's go with the default colors. The custom color scheme looks odd because the selection color for the rest of the text is default only. We could change at some future point if it seems feasible. Thank you!
