### ISSUE TITLE
Max width on elements

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#60]
The elements currently spread the whole area and the posts do not look nice in larger displays. Possible solution is to add max width to the containers for optimal view even when zoomed out.

**Comment by ZahraShahid** [comment]
Can I work on this issue? @gouravkhunger

**Comment by gouravkhunger** [comment]
Yes @ZahraShahid! You are welcome to contribute :)

I didn't add much details to the issue, I'll brief you with the details.

Currently, when the site is zoomed out, the elements stretch because the images and containers don't have max widths:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46792249/193510383-2dc4a1f9-65b4-46d0-a148-bd25c0016c22.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46792249/193510394-3f6d8cd5-5688-4e3f-b2d9-c48d82776a36.png">

Also the width of article and sidebar feels inconsistent:

![CleanShot 2022-10-03 at 11 31 02@2x](https://user-images.githubusercontent.com/46792249/193510484-2a76de8e-37e6-4aae-b73b-3125e4b0ecac.png)

These are the 3 primary things to fix.

The files that need to be updated are:

- [postbox.html](https://github.com/genicsblog/theme-files/blob/main/_includes/postbox.html)
  This is the box for posts, appears on homepage and at the end in section titled "Related content".
- [post.html](https://github.com/genicsblog/theme-files/blob/main/_layouts/post.html)
  This is the template for post pages. Specifies the layout for content, sidebar, comments, etc.
- [header.html](https://github.com/genicsblog/theme-files/blob/main/_includes/header.html#L82-L87)
  This is a general layout for headers. If its included in a post layout, then it has the image and post title. else it shows "Genics Blog" title. You may get a gist by looking at the if & else blocks in this file.

The [local setup](https://github.com/genicsblog/theme-files#local-setup) is pretty simple. The script will download the dependencies and cache them. subsequent runs will be faster.

Let me know if you need more explanations!

**Comment by ZahraShahid** [comment]
Sure, let me take a look at it!
