### ISSUE TITLE
Add tests for scripts

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/theme-files#66]
As the project grows bigger, automated testes for scripts in the [`_scripts`](https://github.com/genicsblog/theme-files/tree/main/_scripts) folder are kind of necessary now.

Some specifics about this task:

- Create sample mock data and test functions present in the files.
- Need not to use some testing library. Testing under workflows via GitHub Actions should do.
- The GH Actions could present fake data to the scripts and validate expected outputs.

**Comment by kailashchoudhary11** [comment]
Can you share any tutorials on this. So that I can learn and work on the issue.
